"""
Django settings for flex_cmdb project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from corsheaders.defaults import default_headers
from config import *


# 基础目录，即项目目录
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# 加密相关
SECRET_KEY = SECRET_KEY


# 调试模式
DEBUG = True


# 域名配置
ALLOWED_HOSTS = ['*']


# 应用列表
INSTALLED_APPS = [
    'django.contrib.sessions',
    'rest_framework',
    'asset'
]


# 中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
]


# 根路由配置
ROOT_URLCONF = 'flex_cmdb.urls'


# WSGI 应用入口
WSGI_APPLICATION = 'flex_cmdb.wsgi.application'


# 数据库
DATABASES = {
     'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': MYSQL_NAME,
        'HOST': MYSQL_HOST,
        'PORT': MYSQL_PORT,
        'USER': MYSQL_USER,
        'PASSWORD': MYSQL_PASSWORD
    }
}


# 国际化配置
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# DRF 配置
REST_FRAMEWORK = {
    # 'DEFAULT_PAGINATION_CLASS': 'common.paginator.Paginator',
    # 'EXCEPTION_HANDLER': 'common.views.exception_handler',
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S'
}


# CORS 跨域配置
CORS_ORIGIN_WHITELIST = (
    'http://localhost:8080',
    'http://op-web.ijunhai.com',
)

CORS_ALLOW_HEADERS = default_headers + (
    'X-Junhai-Token',
    'Access-Control-Allow-Origin'
)

CORS_ALLOW_CREDENTIALS = True